[project]
name = "stellar-m2m"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Davoski1", email = "adeoladavid176@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "stellar-sdk>=16.0.0",
]

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
